apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ec2graviton
spec:
  template:
    spec:
      nodeClassRef:
        name: ec2graviton
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m"] # general-purpose instance type; add more as needed ["c", "r", "g"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]